services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
      - DATABASE_URL=postgresql://postgres:${WEBUI_POSTGRES_PW}@open-webui-postgres/openwebui
      - ENABLE_WEBSOCKET_SUPPORT=true
      - WEBSOCKET_REDIS_URL=redis://open-webui-redis:6379/0
      - REDIS_URL=redis://open-webui-redis:6379/0
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: open-webui-pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pipelines:/app/pipelines/
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: open-webui-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    #    ports:
    #      - "5432:5432" Expose this port if you'd like to dig around in the database
    restart: unless-stopped
    #shm_size: 2g
    environment:
      - POSTGRES_PASSWORD=${WEBUI_POSTGRES_PW}
      - POSTGRES_DB=openwebui
      - PGUSER=postgres
    #command: -c 'shared_buffers=2GB'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      start_period: 5s
      interval: 10s
    
  redis:
    image: redis:7-alpine
    container_name: open-webui-redis
    networks:
      default: null
    restart: unless-stopped
    entrypoint:
      - redis-server
      - --save 60 1
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      start_period: 20s
      interval: 10s

volumes:
  ollama: {}
  open-webui: {}
  pipelines: {}
  postgres: {}
